version: '3.8'
networks:
  postgres-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
services:
  postgres:
    image: postgres:10.3
    container_name: postgres-docker
    restart: always
    networks:
      - postgres-network
    environment:
      - POSTGRES_USER=${__YOUR_DATABASE_USER__}
      - POSTGRES_PASSWORD=${__YOUR_DATABASE_PASSWORD__}
      - POSTGRES_DB=${__YOUR_DATABASE_NAME__}
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - '${__YOUR_DATABASE_PORT__}:${__YOUR_DATABASE_PORT__}'
    expose:
      - '${__YOUR_DATABASE_PORT__}'
  # prisma:
  #   container_name: dockerprisma
  #   build: 
  #     context: ./                   
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - ${__YOUR_PRISMA_SERVER_PORT__}:${__YOUR_PRISMA_SERVER_PORT__}
  #   networks:
  #     - postgres-network
  #   command: >
  #     bash -c '
  #       npx prisma generate
  #       npx prisma db push
  #       yarn start
  #     '
  #   depends_on:
  #     - postgres
  #   environment:
  #     PRISMA_CONFIG: |
  #       managementApiSecret: ${__YOUR_MANAGEMENT_API_SECRET__}
  #       port: ${__YOUR_PRISMA_SERVER_PORT__}
  #       databases:
  #         default:
  #           connector: ${__YOUR_DATABASE_CONNECTOR__}
  #           host: ${__YOUR_DATABASE_HOST__}
  #           port: ${__YOUR_DATABASE_PORT__}
  #           user: ${__YOUR_DATABASE_USER__}
  #           password: ${__YOUR_DATABASE_PASSWORD__}
  #           connectionLimit: ${__YOUR_CONNECTION_LIMIT__}
volumes:
  # data-prisma:
  data-postgres: